version: "3" 
services:
  web_dribbbleclonewsl:
    image: alexrogna/dribbbleclonewsl_web:prod
    expose:
      - 3000
    env_file:
      - .env/production/database_dribbbleclonewsl
      - .env/production/web_dribbbleclonewsl
    environment:
      - VIRTUAL_HOST=dribbbleclonewsl.alexrogna.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=dribbbleclonewsl.alexrogna.com
    networks:
      - proxy
    restart: always

  database_dribbbleclonewsl:
    image: postgres
    env_file:
      - .env/production/database_dribbbleclonewsl
    volumes:
      - db_data_dribbbleclonewsl:/var/lib/postgresql/data
    networks:
      - proxy
    restart: always
    
  db-migrator_dribbbleclonewsl:
    image: alexrogna/dribbbleclonewsl_web:prod
    command: ["./wait-for", "--timeout=300", "database_dribbbleclonewsl:5432", "--", "bin/rails", "db:create" , "db:migrate"]
    env_file:
      - .env/production/database_dribbbleclonewsl
      - .env/production/web_dribbbleclonewsl
    networks:
      - proxy
volumes:
  db_data_dribbbleclonewsl:
networks:
  proxy: